### ISSUE TITLE
Investigate Python dependencies

### ISSUE THREAD

**Issue by mgsdk** [TFJTFJ/ca-project#2]
Fill out requirements.txt

**Comment by mgsdk** [comment]
pip install Flask
pip install SQLAlchemy
pip install flask_sqlalchemy
pip install flask_wtf

**Comment by EmilMunk** [comment]
Flask==0.12.2
 SQLAlchemy==1.1.13
 flask-sqlalchemy==2.2
flask-wtf==0.14.2
